language: ruby
rvm:
  - 2.1.5
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database markdown-drive_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare --trace
script:
  - RAILS_ENV=test bundle exec rake spec

