language: ruby
rvm:
  - 2.1.2
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:seed --trace
  - bundle exec rake db:test:prepare --trace
script:
  - RAILS_ENV=test bundle exec rake spec
gemfile: 
  - Gemfile

